# Add your code below

version: '3.1'

services:
  hyper-service:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    networks:
      - hyper-task-manager-network
    depends_on:
      - mongodb
    container_name: hyper-task-manager
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: "mongodb"
      MONGO_PORT_NUMBER: "27017"




  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  mongo-data:
networks:
  hyper-task-manager-network:



